[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
nft_staking_metadata = "2A8PvxwNyoqdfEQKEGAo9PgByToghe4VJcCfcARAHNrd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/xeony/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
